import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "TalkNow | Information and Communication Technology",
  description: "Generated by create next app",
  robots: {
    follow: false,
    index: false,
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-x-hidden w-full bg-gray-950 text-gray-50 min-h-screen flex flex-col overflow-y-scroll`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
